# Generated by Django 5.1.1 on 2024-11-30 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='even_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
